@tool
extends Node2D
## Parses a level JSON file and builds it as TileMapLayers + scene instances.
## Generated by python/generate_level_builder.py

##--------------------
## DO NOT EDIT BY HAND
##--------------------

@export_file("*.json") var level_json_path: String = ""

@export var build_level: bool = false:
	set(value):
		if value and Engine.is_editor_hint():
			_build_level()

@export var clear_level: bool = false:
	set(value):
		if value and Engine.is_editor_hint():
			_clear_level()

@export var update_palette: bool = false:
	set(value):
		if value and Engine.is_editor_hint():
			_update_palette()

@export_group("Main Area")
@export var world_theme: Palette.WorldTheme = Palette.WorldTheme.OVERWORLD
@export var scenery_type: Palette.SceneryType = Palette.SceneryType.DEFAULT

@export_group("Subarea 1")
@export var subarea_1_theme: Palette.WorldTheme = Palette.WorldTheme.UNDERGROUND
@export var subarea_1_scenery: Palette.SceneryType = Palette.SceneryType.DEFAULT

@export_group("Subarea 2")
@export var subarea_2_theme: Palette.WorldTheme = Palette.WorldTheme.UNDERGROUND
@export var subarea_2_scenery: Palette.SceneryType = Palette.SceneryType.DEFAULT

const METATILE_PX := 16
const AREA_ROWS := 13
const AREA_GAP := 32

const THEME_FROM_AREA_TYPE := {
	"overworld": Palette.WorldTheme.OVERWORLD,
	"underground": Palette.WorldTheme.UNDERGROUND,
	"castle": Palette.WorldTheme.CASTLE,
	"water": Palette.WorldTheme.UNDERWATER,
}

const LAYER_DEFS: Array[Array] = [
	# [key, display_name, tileset_path, sprite_type]
	[&"background",  "Background",  "res://tilesets/background_tileset.tres",  1],
	[&"scenery",     "Scenery",     "res://tilesets/scenery_tileset.tres",     3],
	[&"atmospheric", "Atmospheric", "res://tilesets/atmospheric_tileset.tres", 6],
	[&"red_enemies", "RedEnemies",  "res://tilesets/red_enemies.tres",        7],
]

# Tileset entries: metatile_id -> [atlas_col, atlas_row, &"layer_key"]
# Scene entries:   metatile_id -> &"res://scenes/sprites/name.tscn"
const METATILE_MAP := {
	2: [0, 13, &"scenery"],
	3: [1, 13, &"scenery"],
	4: [2, 13, &"scenery"],
	5: [6, 11, &"scenery"],
	6: [7, 11, &"scenery"],
	7: [7, 10, &"scenery"],
	8: [8, 11, &"scenery"],
	9: [3, 11, &"scenery"],
	10: [2, 11, &"scenery"],
	11: [2, 7, &"scenery"],
	12: &"res://scenes/sprites/chain.tscn",
	13: [1, 6, &"scenery"],
	14: [0, 7, &"scenery"],
	15: [1, 7, &"scenery"],
	16: [7, 5, &"scenery"],
	17: [8, 5, &"scenery"],
	18: [7, 5, &"scenery"],
	19: [8, 5, &"scenery"],
	20: [7, 6, &"scenery"],
	21: [8, 6, &"scenery"],
	22: [0, 5, &"scenery"],
	23: [2, 5, &"scenery"],
	24: [3, 5, &"scenery"],
	25: [4, 5, &"scenery"],
	26: [5, 5, &"scenery"],
	27: [6, 5, &"scenery"],
	28: [5, 7, &"scenery"],
	29: [6, 7, &"scenery"],
	30: [7, 7, &"scenery"],
	31: [5, 8, &"scenery"],
	32: [6, 8, &"scenery"],
	33: [7, 8, &"scenery"],
	34: [4, 7, &"scenery"],
	36: [3, 8, &"scenery"],
	37: [2, 8, &"scenery"],
	64: [3, 3, &"background"],
	65: [2, 2, &"background"],
	66: [1, 2, &"background"],
	67: [3, 2, &"background"],
	69: [4, 0, &"background"],
	70: [3, 1, &"background"],
	71: [2, 0, &"background"],
	72: [5, 1, &"background"],
	73: [5, 0, &"background"],
	74: [6, 0, &"background"],
	75: [6, 1, &"background"],
	76: [1, 1, &"background"],
	77: [2, 3, &"background"],
	78: [1, 3, &"background"],
	79: [4, 2, &"background"],
	80: [4, 3, &"background"],
	81: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "empty"}],
	82: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "empty"}],
	83: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "empty"}],
	84: [0, 0, &"background"],
	85: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "vine"}],
	86: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "star"}],
	87: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "multi_coin"}],
	88: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "one_up"}],
	89: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "vine"}],
	90: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "star"}],
	91: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "multi_coin"}],
	92: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "one_up"}],
	93: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "empty"}],
	94: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "empty"}],
	95: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "invisible_coin"}],
	96: [&"res://scenes/sprites/brick_bg.tscn", {&"contents": "invisible_one_up"}],
	97: [0, 1, &"background"],
	98: [0, 3, &"background"],
	100: &"res://scenes/sprites/cannon_top.tscn",
	101: &"res://scenes/sprites/cannon_mid.tscn",
	102: &"res://scenes/sprites/cannon_base.tscn",
	105: [0, 2, &"background"],
	128: [12, 0, &"atmospheric"],
	129: [13, 0, &"atmospheric"],
	130: [14, 0, &"atmospheric"],
	131: [12, 1, &"atmospheric"],
	132: [13, 1, &"atmospheric"],
	133: [14, 1, &"atmospheric"],
	134: [13, 3, &"atmospheric"],
	135: [14, 3, &"atmospheric"],
	136: &"res://scenes/sprites/cloud_small.tscn",
	137: [15, 3, &"atmospheric"],
	192: [&"res://scenes/sprites/question_block.tscn", {&"contents": "coin"}],
	193: [&"res://scenes/sprites/question_block.tscn", {&"contents": "powerup"}],
	194: &"res://scenes/sprites/coin_a.tscn",
	195: &"res://scenes/sprites/coin_b.tscn",
	196: [&"res://scenes/sprites/block_empty_bg.tscn", {&"contents": "fireball"}],
	197: &"res://scenes/sprites/axe.tscn",
}

# Entity type → [scene_path, sprite_height_px]
const ENTITY_SCENE_MAP := {
	"goomba": ["res://scenes/enemies/goomba.tscn", 16],
	"koopa_green": ["res://scenes/enemies/koopa_troopa.tscn", 24],
	"koopa_red": ["res://scenes/enemies/koopa_troopa.tscn", 24],
	"koopa_para_jump_green": ["res://scenes/enemies/paratroopa.tscn", 24],
	"koopa_para_fly_green": ["res://scenes/enemies/paratroopa.tscn", 24],
	"koopa_para_fly_red": ["res://scenes/enemies/paratroopa.tscn", 24],
	"koopa_para_jump_red": ["res://scenes/enemies/paratroopa.tscn", 24],
	"buzzy_beetle": ["res://scenes/enemies/buzzy_beetle.tscn", 16],
	"blooper": ["res://scenes/enemies/blooper.tscn", 24],
	"cheep_red": ["res://scenes/enemies/cheep_cheep.tscn", 16],
	"cheep_grey": ["res://scenes/enemies/cheep_cheep.tscn", 16],
	"cheep_fly": ["res://scenes/enemies/cheep_cheep.tscn", 16],
	"hammer_bro": ["res://scenes/enemies/hammer_bro.tscn", 24],
	"lakitu": ["res://scenes/enemies/lakitu.tscn", 24],
	"piranha_plant": ["res://scenes/enemies/piranha_plant.tscn", 24],
	"spiny": ["res://scenes/enemies/spiny.tscn", 16],
	"podoboo": ["res://scenes/enemies/podoboo.tscn", 16],
	"bowser": ["res://scenes/enemies/bowser.tscn", 32],
	"bullet": ["res://scenes/enemies/bullet_bill.tscn", 16],
	"spring": ["res://scenes/enemies/springboard.tscn", 24],
	"toad": ["res://scenes/enemies/toad.tscn", 24],
	"princess": ["res://scenes/enemies/princess.tscn", 24],
	"plat_std_h": ["res://scenes/sprites/platform_moving_longer.tscn", 16, {"movement_type": 0}],
	"plat_std_h_b": ["res://scenes/sprites/platform_moving_longer.tscn", 16, {"movement_type": 0}],
	"plat_std_v": ["res://scenes/sprites/platform_moving_longer.tscn", 16, {"movement_type": 1}],
	"plat_l_up": ["res://scenes/sprites/platform_moving_longer.tscn", 16, {"movement_type": 2}],
	"plat_s_up": ["res://scenes/sprites/platform_moving_longer.tscn", 16, {"movement_type": 2}],
	"plat_l_down": ["res://scenes/sprites/platform_moving_longer.tscn", 16, {"movement_type": 3}],
	"plat_s_down": ["res://scenes/sprites/platform_moving_longer.tscn", 16, {"movement_type": 3}],
	"plat_drop": ["res://scenes/sprites/platform_moving_longer.tscn", 16, {"movement_type": 4}],
	"plat_bal": ["res://scenes/sprites/platform_moving_longer.tscn", 16, {"movement_type": 5}],
}

# Group spawners: entity_type → [base_scene_path, count, sprite_height_px]
const GROUP_SPAWNER_MAP := {
	"goomba_duo_lo": ["res://scenes/enemies/goomba.tscn", 2, 16],
	"goomba_trio_lo": ["res://scenes/enemies/goomba.tscn", 3, 16],
	"goomba_duo_hi": ["res://scenes/enemies/goomba.tscn", 2, 16],
	"goomba_trio_hi": ["res://scenes/enemies/goomba.tscn", 3, 16],
	"koopa_duo_lo": ["res://scenes/enemies/koopa_troopa.tscn", 2, 24],
	"koopa_trio_lo": ["res://scenes/enemies/koopa_troopa.tscn", 3, 24],
	"koopa_duo_hi": ["res://scenes/enemies/koopa_troopa.tscn", 2, 24],
	"koopa_trio_hi": ["res://scenes/enemies/koopa_troopa.tscn", 3, 24],
}


func _update_palette() -> void:
	var shader := load("res://scripts/palette_swap.gdshader") as Shader
	for i in range(get_child_count()):
		var area_node := get_child(i)
		if not area_node is Node2D:
			continue

		var theme: Palette.WorldTheme
		var scenery: Palette.SceneryType
		if i == 0:
			theme = world_theme
			scenery = scenery_type
		elif i == 1:
			theme = subarea_1_theme
			scenery = subarea_1_scenery
		elif i == 2:
			theme = subarea_2_theme
			scenery = subarea_2_scenery
		else:
			continue

		for child in area_node.get_children():
			if child is TileMapLayer:
				var sprite_type: int = child.get(&"sprite_type")
				var pal_id: int = Palette.PALETTE_TABLE[sprite_type][theme]
				if sprite_type == 3 and Palette.SCENERY_OVERRIDE.has(scenery):
					pal_id = Palette.SCENERY_OVERRIDE[scenery]
				var mat := child.material as ShaderMaterial
				if mat == null:
					mat = ShaderMaterial.new()
					mat.shader = shader
					child.material = mat
				mat.set_shader_parameter("palette_id", pal_id)
	print("[LevelBuilder] Palettes updated")


func _clear_level() -> void:
	for i in range(get_child_count() - 1, -1, -1):
		var child := get_child(i)
		remove_child(child)
		child.free()
	print("[LevelBuilder] Cleared all children")


func _build_area(parent: Node2D, grid: Array, rows: int, cols: int,
		theme: Palette.WorldTheme, scenery: Palette.SceneryType) -> Dictionary:
	var root := get_tree().edited_scene_root
	var shader := load("res://scripts/palette_swap.gdshader") as Shader
	var pal_script := load("res://scripts/palette_swap.gd") as Script

	var layers: Dictionary = {}
	for def in LAYER_DEFS:
		var key: StringName = def[0]
		var display: String = def[1]
		var tileset_path: String = def[2]
		var sprite_type: int = def[3]
		var pal_id: int = Palette.PALETTE_TABLE[sprite_type][theme]
		if sprite_type == 3 and Palette.SCENERY_OVERRIDE.has(scenery):
			pal_id = Palette.SCENERY_OVERRIDE[scenery]

		var layer := TileMapLayer.new()
		layer.name = display
		layer.tile_set = load(tileset_path)

		var mat := ShaderMaterial.new()
		mat.shader = shader
		mat.set_shader_parameter("palette_id", pal_id)
		layer.material = mat

		layer.set_script(pal_script)
		layer.set(&"sprite_type", sprite_type)

		parent.add_child(layer)
		layer.owner = root
		layers[key] = layer

	var scenes_node := Node2D.new()
	scenes_node.name = "Scenes"
	parent.add_child(scenes_node)
	scenes_node.owner = root

	var placed_tiles := 0
	var placed_scenes := 0
	var unknown: Dictionary = {}

	for row_idx in range(rows):
		var row_data: Array = grid[row_idx]
		for col_idx in range(cols):
			var mid: int = int(row_data[col_idx])
			if mid == 0:
				continue
			if not METATILE_MAP.has(mid):
				unknown[mid] = unknown.get(mid, 0) + 1
				continue

			var entry = METATILE_MAP[mid]
			if entry is StringName or entry is String:
				var scene := load(str(entry)) as PackedScene
				if scene:
					var inst := scene.instantiate()
					inst.position = Vector2(col_idx * METATILE_PX, row_idx * METATILE_PX)
					scenes_node.add_child(inst)
					inst.owner = root
					placed_scenes += 1
			elif entry is Array and entry.size() == 2 and (entry[0] is StringName or entry[0] is String):
				var scene := load(str(entry[0])) as PackedScene
				if scene:
					var inst := scene.instantiate()
					inst.position = Vector2(col_idx * METATILE_PX, row_idx * METATILE_PX)
					var props: Dictionary = entry[1]
					for prop_name in props:
						inst.set(prop_name, props[prop_name])
					scenes_node.add_child(inst)
					inst.owner = root
					placed_scenes += 1
			elif entry is Array:
				var layer: TileMapLayer = layers[entry[2]]
				layer.set_cell(Vector2i(col_idx, row_idx), 0, Vector2i(entry[0], entry[1]))
				placed_tiles += 1

	return {"tiles": placed_tiles, "scenes": placed_scenes, "unknown": unknown}


func _build_entities(parent: Node2D, entities: Array) -> int:
	var root := get_tree().edited_scene_root
	var entities_node := Node2D.new()
	entities_node.name = "Entities"
	parent.add_child(entities_node)
	entities_node.owner = root

	var placed := 0
	for entity in entities:
		var etype: String = entity["type"]
		var col: int = int(entity["col"])
		var row: int = int(entity["row"])
		if ENTITY_SCENE_MAP.has(etype):
			var entry: Array = ENTITY_SCENE_MAP[etype]
			var scene := load(entry[0]) as PackedScene
			var h: int = entry[1]
			if scene:
				var inst := scene.instantiate()
				inst.position = Vector2(col * METATILE_PX, row * METATILE_PX - h)
				if entry.size() > 2:
					var props: Dictionary = entry[2]
					for prop_name in props:
						inst.set(prop_name, props[prop_name])
				entities_node.add_child(inst)
				inst.owner = root
				placed += 1
		elif GROUP_SPAWNER_MAP.has(etype):
			var group_def: Array = GROUP_SPAWNER_MAP[etype]
			var scene := load(group_def[0]) as PackedScene
			var count: int = group_def[1]
			var h: int = group_def[2]
			if scene:
				for i in range(count):
					var inst := scene.instantiate()
					inst.position = Vector2((col + i) * METATILE_PX, row * METATILE_PX - h)
					entities_node.add_child(inst)
					inst.owner = root
					placed += 1

	return placed


func _build_level() -> void:
	if level_json_path.is_empty():
		push_error("[LevelBuilder] No level JSON path set")
		return

	var file := FileAccess.open(level_json_path, FileAccess.READ)
	if not file:
		push_error("[LevelBuilder] Cannot open: %s" % level_json_path)
		return

	var data = JSON.parse_string(file.get_as_text())
	file.close()
	if data == null:
		push_error("[LevelBuilder] Failed to parse JSON")
		return

	_clear_level()

	var root := get_tree().edited_scene_root
	var areas: Array = data["areas"]
	var all_unknown: Dictionary = {}
	var y_offset := 0.0

	# Auto-set themes from JSON area_type_name
	if areas.size() > 0:
		var main_type: String = areas[0].get("area_type_name", "overworld")
		world_theme = THEME_FROM_AREA_TYPE.get(main_type, Palette.WorldTheme.OVERWORLD)
	if areas.size() > 1:
		var sub1_type: String = areas[1].get("area_type_name", "underground")
		subarea_1_theme = THEME_FROM_AREA_TYPE.get(sub1_type, Palette.WorldTheme.UNDERGROUND)
	if areas.size() > 2:
		var sub2_type: String = areas[2].get("area_type_name", "underground")
		subarea_2_theme = THEME_FROM_AREA_TYPE.get(sub2_type, Palette.WorldTheme.UNDERGROUND)
	notify_property_list_changed()

	for i in range(areas.size()):
		var area: Dictionary = areas[i]
		var area_name: String = area.get("name", "Area_%d" % i)
		var area_rows: int = int(area["rows"])
		var area_cols: int = int(area["cols"])
		var area_type_name: String = area.get("area_type_name", "overworld")

		var theme: Palette.WorldTheme
		var scenery: Palette.SceneryType
		if i == 0:
			theme = world_theme
			scenery = scenery_type
		elif i == 1:
			theme = subarea_1_theme
			scenery = subarea_1_scenery
		elif i == 2:
			theme = subarea_2_theme
			scenery = subarea_2_scenery
		else:
			theme = THEME_FROM_AREA_TYPE.get(area_type_name, Palette.WorldTheme.OVERWORLD)
			scenery = Palette.SceneryType.DEFAULT

		var area_node := Node2D.new()
		area_node.name = area_name
		if y_offset != 0.0:
			area_node.position.y = y_offset
		add_child(area_node)
		area_node.owner = root

		var result := _build_area(area_node, area["grid"],
				area_rows, area_cols, theme, scenery)

		var entity_count := 0
		var entities: Array = area.get("entities", [])
		if entities.size() > 0:
			entity_count = _build_entities(area_node, entities)

		print("[LevelBuilder] %s: %d tiles, %d scenes, %d entities (%dx%d)" % [
				area_name, result["tiles"], result["scenes"], entity_count, area_cols, area_rows])

		for k in result["unknown"]:
			all_unknown[k] = all_unknown.get(k, 0) + result["unknown"][k]

		y_offset += AREA_ROWS * METATILE_PX + AREA_GAP

	if all_unknown.size() > 0:
		var sorted_keys := all_unknown.keys()
		sorted_keys.sort()
		for k in sorted_keys:
			print("[LevelBuilder]   unknown metatile %d  ×%d" % [k, all_unknown[k]])
